export { default as Home } from './Home';
export { default as Login } from './Login';
export { default as Register } from './Register';
export { default as About } from './About';
export { default as MainPage } from './MainPage';
export { default as Navbar } from './Navbar';
export { default as CreateGoal } from './CreateGoal';
export { default as UpdateGoal } from './UpdateGoal';
export { default as Achievements } from './Achievements';